source "https://rubygems.org"

# needed gems
gem 'activerecord', '~> 7.1', '>= 7.1.2'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.27'
gem 'bundler', '~> 2.5', '>= 2.5.4'
gem 'require_all', '~> 1.3', '>= 1.3.3'
gem 'json'
gem 'rake', '~> 13.1'
gem 'base64', '~> 0.2.0'

# development
group :development do
    gem 'sqlite3', '~> 1.7'
    gem 'rspec', '~> 3.12'
    gem 'pry', '~> 0.14.2'
    gem 'faker', '~> 3.2', '>= 3.2.2'
end

group :production do
    gem 'pg', '~> 1.5', '>= 1.5.4'
end